Update Virtual Machine Chart Configuration and Documentation
aenix-io/cozystack pull request #292
Opened 2024-08-17 18:02 UTC by artemrootman

- Refactored `values.yaml` to move disk size under `resources` and added `service.ports` configuration.
- Updated `README.md` to include detailed parameter descriptions and example configuration.
- Modified `service.yaml` to use dynamic port configuration from `values.yaml`.
- Corrected `vm.yaml` to reference disk size from `resources` and updated base image URL for Fedora.
- Revised `values.schema.json` to align with changes in `values.yaml`, including added parameters and descriptions.

Enhancements include:
- Improved clarity of default values and parameter settings.
- Added flexibility for service port customization.
- Corrected and updated URLs and default values for better accuracy.

2024-08-18 23:07 UTC, themoriarti approved these changes
Looks good

2024-08-19 07:54 UTC, kvaps requested changes
Thank you for your contribution!

2024-08-19 07:54 UTC, kvaps commented on packages/apps/virtual-machine/README.md
> +ssh_key: YOUR_SSH_PUB_KEY_HERE
Let's make multiple `sshKeys` instead of signle one

```suggestion
sshKeys:
- YOUR_SSH_PUB_KEY_HERE
```

2024-08-19 07:54 UTC, kvaps commented on packages/apps/virtual-machine/README.md
> +ssh_key: YOUR_SSH_PUB_KEY_HERE
keys in values.yaml should be `camelCase` instead of `snake_case`

```suggestion
sshPwauth: true
disableRoot: true
password: hackme
chpasswdExpire: false
sshKey: YOUR_SSH_PUB_KEY_HERE
```

2024-08-19 07:54 UTC, kvaps commented on packages/apps/virtual-machine/templates/vm.yaml
> +            - {{ .Values.ssh_key }}
```suggestion
            {{- if .Values.sshKeys }}
            ssh_authorized_keys:
            {{- range .Values.sshKeys }}
            - {{ . }}
            {{- end }}
            {{- end }}
```

2024-08-19 09:31 UTC, artemrootman commented on packages/apps/virtual-machine/README.md
> +ssh_key: YOUR_SSH_PUB_KEY_HERE
That's a good idea.
What keys should we suggest as an example? What do you think about that?
 ```
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr2N...
- ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr3Z...
```

2024-08-19 09:32 UTC, gecube commented on packages/apps/virtual-machine/README.md
> +ssh_key: YOUR_SSH_PUB_KEY_HERE
The list would be nice.

2024-08-19 09:33 UTC, gecube commented on packages/apps/virtual-machine/README.md
> +ssh_key: YOUR_SSH_PUB_KEY_HERE
where does the requirement for `camelCase` come from?

2024-08-19 09:48 UTC, kvaps commented on packages/apps/virtual-machine/README.md
> +ssh_key: YOUR_SSH_PUB_KEY_HERE
https://helm.sh/docs/chart_best_practices/values/#naming-conventions

> # Naming Conventions
> 
> 
Variable names should begin with a lowercase letter, and words should be separated with camelcase:

2024-08-19 09:50 UTC, gecube commented on packages/apps/virtual-machine/README.md
> +ssh_key: YOUR_SSH_PUB_KEY_HERE
ok, let it be

2024-08-19 13:02 UTC, kvaps approved these changes
LGTM, thank you!

2024-08-19 13:02 UTC, merged